"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_FIND_NEAREST = exports.REMOVE_DOCKED_CAMERA = exports.DOCK_APP_STATE_RECEIVED = exports.CLEAR_FIND_NEAREST = exports.CLEAR_CAMERA_REPLACE_MODE = exports.CAMERA_TO_DOCK_MODE = exports.CAMERA_PRIORITY_SET = exports.CAMERA_DOCKED = exports.CAMERAS_RECEIVED = void 0;
var DOCK_APP_STATE_RECEIVED = "DOCK_APP_STATE_RECEIVED";
exports.DOCK_APP_STATE_RECEIVED = DOCK_APP_STATE_RECEIVED;
var CAMERAS_RECEIVED = "CAMERAS_RECEIVED";
exports.CAMERAS_RECEIVED = CAMERAS_RECEIVED;
var CAMERA_DOCKED = "CAMERA_DOCKED";
exports.CAMERA_DOCKED = CAMERA_DOCKED;
var REMOVE_DOCKED_CAMERA = "REMOVE_DOCKED_CAMERA";
exports.REMOVE_DOCKED_CAMERA = REMOVE_DOCKED_CAMERA;
var TOGGLE_FIND_NEAREST = "TOGGLE_FIND_NEAREST";
exports.TOGGLE_FIND_NEAREST = TOGGLE_FIND_NEAREST;
var CLEAR_FIND_NEAREST = "CLEAR_FIND_NEAREST";
exports.CLEAR_FIND_NEAREST = CLEAR_FIND_NEAREST;
var CLEAR_CAMERA_REPLACE_MODE = "CLEAR_CAMERA_REPLACE_MODE";
exports.CLEAR_CAMERA_REPLACE_MODE = CLEAR_CAMERA_REPLACE_MODE;
var CAMERA_TO_DOCK_MODE = "CAMERA_TO_DOCK_MODE";
exports.CAMERA_TO_DOCK_MODE = CAMERA_TO_DOCK_MODE;
var CAMERA_PRIORITY_SET = "CAMERA_PRIORITY_SET";
exports.CAMERA_PRIORITY_SET = CAMERA_PRIORITY_SET;