"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.GIS_SERVICE_REMOVED = exports.GIS_SERVICE_RECEIVED = exports.GIS_SERVICES_RECEIVED = exports.GIS_LAYERS_RECEIVED = exports.CREATE_SERVICE_SUCCESS = exports.CREATE_SERVICE_RESET = exports.CREATE_SERVICE_REQUEST = exports.CREATE_SERVICE_FAILURE = void 0;
var GIS_SERVICES_RECEIVED = "GIS_SERVICES_RECEIVED";
exports.GIS_SERVICES_RECEIVED = GIS_SERVICES_RECEIVED;
var CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
exports.CREATE_SERVICE_SUCCESS = CREATE_SERVICE_SUCCESS;
var GIS_LAYERS_RECEIVED = "GIS_LAYERS_RECEIVED";
exports.GIS_LAYERS_RECEIVED = GIS_LAYERS_RECEIVED;
var CREATE_SERVICE_FAILURE = "CREATE_SERVICE_FAILURE";
exports.CREATE_SERVICE_FAILURE = CREATE_SERVICE_FAILURE;
var CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
exports.CREATE_SERVICE_REQUEST = CREATE_SERVICE_REQUEST;
var CREATE_SERVICE_RESET = "CREATE_SERVICE_RESET";
exports.CREATE_SERVICE_RESET = CREATE_SERVICE_RESET;
var GIS_SERVICE_REMOVED = "GIS_SERVICE_REMOVED";
exports.GIS_SERVICE_REMOVED = GIS_SERVICE_REMOVED;
var GIS_SERVICE_RECEIVED = "GIS_SERVICE_RECEIVED";
exports.GIS_SERVICE_RECEIVED = GIS_SERVICE_RECEIVED;