export const GIS_SERVICES_RECEIVED = "GIS_SERVICES_RECEIVED";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const GIS_LAYERS_RECEIVED = "GIS_LAYERS_RECEIVED";
export const CREATE_SERVICE_FAILURE = "CREATE_SERVICE_FAILURE";
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_RESET = "CREATE_SERVICE_RESET";
export const GIS_SERVICE_REMOVED = "GIS_SERVICE_REMOVED";
export const GIS_SERVICE_RECEIVED = "GIS_SERVICE_RECEIVED";
