//App
export const SET_FEED_SUBSCRIPTION = "SET_FEED_SUBSCRIPTION";

// ListPanel
export const TOGGLE_COLLECTION_EXPANDED = "TOGGLE_COLLECTION_EXPANDED";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_GIS_FILTER = "UPDATE_GIS_FILTER";
export const UPDATE_COLLECTIONS_FILTER = "UPDATE_COLLECTIONS_FILTER";
export const SET_TAB = "SET_TAB";
export const SHOW_LIST_PANEL = "SHOW_LIST_PANEL";
export const FILTER_DOCK = "FILTER_DOCK";
export const REMOVED_FROM_MY_ITEMS = "REMOVED_FROM_MY_ITEMS";
export const ADD_TO_FILTER = "ADD_TO_FILTER";
export const REMOVE_FROM_FILTER = "REMOVE_FROM_FILTER";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";
export const VIEW_LAST_PROFILE = "VIEW_LAST_PROFILE";

// EntityProfile
export const SHOW_ENTITY_INFO = "SHOW_ENTITY_INFO";
export const SHOW_GIS_ENTITY_INFO = "SHOW_GIS_ENTITY_INFO";
export const UPDATE_VIEWING_HISTORY = "UPDATE_VIEWING_HISTORY";
export const HIDE_ENTITY_INFO = "HIDE_ENTITY_INFO";
export const ACTIVITY_DATA_RECEIVED = "ACTIVITY_DATA_RECEIVED";
export const ATTACHMENT_DATA_RECEIVED = "ATTACHMENT_DATA_RECEIVED";
export const GET_ACTIVITY_BATCH = "GET_ACTIVITY_BATCH";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const TRACK_HISTORY_TOGGLED = "TRACK_HISTORY_TOGGLED";
export const IS_WAITING_ON_REQUEST = "IS_WAITING_ON_REQUEST";

// MapBase
export const SET_MAP_REFERENCE = "SET_MAP_REFERENCE";
export const DISABLE_LAYERS = "DISABLE_LAYERS";
export const ENABLE_LAYERS = "ENABLE_LAYERS";

// LayerSources
export const SET_LAYER_OPACITY = "SET_LAYER_OPACITY";
export const TOGGLE_DISTANCE_TOOLS = "TOGGLE_DISTANCE_TOOLS";
export const FETCH_GIS_DATA_SUCCESS = "FETCH_GIS_DATA_SUCCESS";

// MapAppBar
export const TOGGLE_APP_SETTINGS_MENU = "TOGGLE_APP_SETTINGS_MENU";
export const TOGGLE_ENTITY_LABELS = "TOGGLE_ENTITY_LABELS";
export const TOGGLE_MAP_POINTS = "TOGGLE_MAP_POINTS";
export const TOGGLE_MAP_POLYGONS = "TOGGLE_MAP_POLYGONS";
export const TOGGLE_MAP_LINES = "TOGGLE_MAP_LINES";
export const USE_MAPBOX_SERVER = "USE_MAPBOX_SERVER";
export const TOGGLE_MAP_TRACKS = "TOGGLE_MAP_TRACKS";
export const TOGGLE_GRAYSCALE_MAP = "TOGGLE_GRAYSCALE_MAP";
export const SET_MAP_STYLE = "SET_MAP_STYLE";
export const TOGGLE_MAP_OVERLAY = "TOGGLE_MAP_OVERLAY";
export const TOGGLE_MAP_FEEDS_SUCCESS = "TOGGLE_MAP_FEEDS_SUCCESS";
export const TOGGLE_MAP_GIS_LAYER_SUCCESS = "TOGGLE_MAP_GIS_LAYER_SUCCESS";

// LayoutControls
export const SET_WIDGET_ORDER = "SET_WIDGET_ORDER";

// Rules
export const RULES_RECIEVED = "RULES_RECIEVED";

// Event Card & Profile
export const SHOW_EVENT_PROFILE = "SHOW_EVENT_PROFILE";
export const PINNED_ITEM_RECEIVED = "PINNED_ITEM_RECEIVED";
export const EVENT_RECEIVED = "EVENT_RECEIVED";
export const EVENTS_RECEIVED = "EVENTS_RECEIVED";
export const RECEIVED_COMMENT_COUNT = "RECEIVED_COMMENT_COUNT";
export const UPDATE_EVENT_SEARCH = "UPDATE_EVENT_SEARCH";
export const LISTS_RECEIVED = "LISTS_RECEIVED";
export const LIST_UPDATED = "LIST_UPDATED";
export const LIST_DELETED = "LIST_DELETED";
export const UPDATE_LIST_CHECKBOX = "UPDATE_LIST_CHECKBOX";
export const LISTS_CREATED_BY_TEMPLATE = "LISTS_CREATED_BY_TEMPLATE";
export const SELECT_WIDGET = "SELECT_WIDGET";
export const OPEN_PUBLISH_DIALOG = "OPEN_PUBLISH_DIALOG";
export const OPEN_DELETE_DIALOG = "OPEN_DELETE_DIALOG";
export const OPEN_PIN_DIALOG = "OPEN_PIN_DIALOG";
export const UPDATE_ACTIVITY_FILTER_SUCCESS = "UPDATE_ACTIVITY_FILTER_SUCCESS";
export const SET_EVENT_WIDGET_ORDER = "SET_EVENT_WIDGET_ORDER";
export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const UNPIN_ITEM_SUCCESS = "UNPIN_ITEM_SUCCESS";
export const STREAMED_LIST_RECEIVED = "STREAMED_LIST_RECEIVED";
export const STREAMED_LIST_UPDATED = "STREAMED_LIST_UPDATED";
export const SET_LIST_SUBSCRIPTION = "SET_LIST_SUBSCRIPTION";
export const CLEAR_EVENT_LIST_DATA = "CLEAR_EVENT_LIST_DATA";
export const CLEAR_ACTIVITY_DATA = "CLEAR_ACTIVITY_DATA";
export const SET_ACTIVITY_SUBSCRIPTION = "SET_ACTIVITY_SUBSCRIPTION";
export const EVENT_ACTIVITY_DATA_RECEIVED = "EVENT_ACTIVITY_DATA_RECEIVED";
export const ORGS_RECEIVED = "ORGS_RECEIVED";
export const SHOW_EVENT_ENTITY_INFO = "SHOW_EVENT_ENTITY_INFO";

// Camera Related
export const CAMERAS_RECEIVED = "CAMERAS_RECEIVED";
export const CAMERA_RECEIVED = "CAMERA_RECEIVED";
export const SHOW_CAMERA_PROFILE = "SHOW_CAMERA_PROFILE";
export const RECEIVED_FOV = "RECEIVED_FOV";
export const RECEIVED_FOV_BATCH = "RECEIVED_FOV_BATCH";
export const RECEIVED_FOV_ITEM = "RECEIVED_FOV_ITEM";
export const REMOVED_FOV_ITEM = "REMOVED_FOV_ITEM";
export const SET_FOV_SUBSCRIPTION = "SET_FOV_SUBSCRIPTION";
export const CAMERA_ACTIVITY_DATA_RECEIVED = "CAMERA_ACTIVITY_DATA_RECEIVED";
export const LOAD_CAMERA_ACTIVITIES = "LOAD_CAMERA_ACTIVITIES";
export const CLEAR_CAMERA_ACTIVITY_DATA = "CLEAR_CAMERA_ACTIVITY_DATA";
export const UPDATE_CAMERA_ACTIVITY_FILTER_SUCCESS =
	"UPDATE_CAMERA_ACTIVITY_FILTER_SUCCESS";
export const CAMERA_ATTACHMENT_DATA_RECEIVED =
	"CAMERA_ATTACHMENT_DATA_RECEIVED";
export const CAMERA_ATTACHMENT_DELETE_SUCCESS =
	"CAMERA_ATTACHMENT_DELETE_SUCCESS";
export const CLOSE_CAMERA_DIALOG = "CLOSE_CAMERA_DIALOG";
export const CAMERA_UPDATED = "CAMERA_UPDATED";
export const OPEN_CAMERA_DIALOG = "OPEN_CAMERA_DIALOG";
export const SET_CAMERA_WIDGET_ORDER = "SET_CAMERA_WIDGET_ORDER";
//
export const CAMERA_TO_DOCK_MODE = "CAMERA_TO_DOCK_MODE";
export const CAMERAS_IN_RANGE_RECEIVED = "CAMERAS_IN_RANGE_RECEIVED";
export const CAMERAS_IN_RANGE_REMOVED = "CAMERAS_IN_RANGE_REMOVED";
export const SET_CAMERAS_IN_RANGE_SUBSCRIPTION = "SET_CAMERAS_IN_RANGE_SUBSCRIPTION";
export const CAMERA_IN_RANGE_VIDEO_STREAM_RECEIVED = "CAMERA_IN_RANGE_VIDEO_STREAM_RECEIVED";
export const CAMERA_IN_RANGE_SUBSCRIPTION_RECEIVED = "CAMERA_IN_RANGE_SUBSCRIPTION_RECEIVED";
// Camera Streaming
export const CAMERA_SUBSCRIPTION_RECEIVED = "CAMERA_SUBSCRIPTION_RECEIVED";
export const CAMERA_VIDEO_STREAM_RECEIVED = "CAMERA_VIDEO_STREAM_RECEIVED";

// Facilities
export const FLOOR_PLAN_SELECT = "FLOOR_PLAN_SELECT";
export const FLOOR_PLANS_SET = "FLOOR_PLANS_SET";
export const FLOOR_PLAN_CLEAR = "FLOOR_PLAN_CLEAR";

//Transactions
export const TRANSACTIONS_RECEIVED = "TRANSACTIONS_RECEIVED";
export const ALERTS_RECEIVED = "ALERTS_RECEIVED";
export const PLAYBAR_ALERTS_RECEIVED = "PLAYBAR_ALERTS_RECEIVED";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";