"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_VIEWING_HISTORY = exports.SHRINK_SECONDARY = exports.SET_SELECTED_CONTEXT = exports.OPEN_SECONDARY = exports.OPEN_PRIMARY = exports.EXPAND_SECONDARY = exports.CLOSE_SECONDARY = exports.CLOSE_PRIMARY = exports.CLEAR_VIEWING_HISTORY = exports.CLEAR_SELECTED_CONTEXT = void 0;
var OPEN_PRIMARY = "OPEN_PRIMARY";
exports.OPEN_PRIMARY = OPEN_PRIMARY;
var OPEN_SECONDARY = "OPEN_SECONDARY";
exports.OPEN_SECONDARY = OPEN_SECONDARY;
var CLOSE_PRIMARY = "CLOSE_PRIMARY";
exports.CLOSE_PRIMARY = CLOSE_PRIMARY;
var CLOSE_SECONDARY = "CLOSE_SECONDARY";
exports.CLOSE_SECONDARY = CLOSE_SECONDARY;
var EXPAND_SECONDARY = "EXPAND_SECONDARY";
exports.EXPAND_SECONDARY = EXPAND_SECONDARY;
var SHRINK_SECONDARY = "SHRINK_SECONDARY";
exports.SHRINK_SECONDARY = SHRINK_SECONDARY;
var UPDATE_VIEWING_HISTORY = "UPDATE_VIEWING_HISTORY";
exports.UPDATE_VIEWING_HISTORY = UPDATE_VIEWING_HISTORY;
var SET_SELECTED_CONTEXT = "SET_SELECTED_CONTEXT";
exports.SET_SELECTED_CONTEXT = SET_SELECTED_CONTEXT;
var CLEAR_SELECTED_CONTEXT = "CLEAR_SELECTED_CONTEXT";
exports.CLEAR_SELECTED_CONTEXT = CLEAR_SELECTED_CONTEXT;
var CLEAR_VIEWING_HISTORY = "CLEAR_VIEWING_HISTORY";
exports.CLEAR_VIEWING_HISTORY = CLEAR_VIEWING_HISTORY;