export const FACILITY_ADD = "FACILITY_ADD";
export const SET_PRELOADED = "SET_PRELOADED";

// Widget Launch
export const SET_WIDGET_LAUNCH_DATA = "SET_WIDGET_LAUNCH_DATA";

// Import Facilities
export const IMPORT_FLOORPLAN_ADDED = "IMPORT_FLOORPLAN_ADDED";
export const IMPORT_FACILITIES_DONE = "IMPORT_FACILITIES_DONE";
export const IMPORT_FACILITIES_ERROR = "IMPORT_FACILITIES_ERROR";
