export const OPEN_EVENT_FORM = "OPEN_EVENT_FORM";
export const OPEN_BERTH_MAP = "OPEN_BERTH_MAP";
export const CLOSE_BERTH_MAP = "CLOSE_BERTH_MAP";
export const TRACK_RECEIVED = "TRACK_RECEIVED";
export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION";
export const REMOVE_SUBSCRIPTIONS = "REMOVE_SUBSCRIPTIONS";
export const UPDATE_VIEW = "UPDATE_VIEW";
