"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.SYSTEM_NOTIFICATION_ACKNOWLEDGED = exports.SYSTEM_NOTIFICATIONS_RECEIVED = exports.SYSTEM_NOTIFICATIONS_CLEARED = void 0;
var SYSTEM_NOTIFICATIONS_RECEIVED = "SYSTEM_NOTIFICATIONS_RECEIVED";
exports.SYSTEM_NOTIFICATIONS_RECEIVED = SYSTEM_NOTIFICATIONS_RECEIVED;
var SYSTEM_NOTIFICATION_ACKNOWLEDGED = "SYSTEM_NOTIFICATION_ACKNOWLEDGED";
exports.SYSTEM_NOTIFICATION_ACKNOWLEDGED = SYSTEM_NOTIFICATION_ACKNOWLEDGED;
var SYSTEM_NOTIFICATIONS_CLEARED = "SYSTEM_NOTIFICATIONS_CLEARED";
exports.SYSTEM_NOTIFICATIONS_CLEARED = SYSTEM_NOTIFICATIONS_CLEARED;