// App
export const APP_STATE_RECEIVED = "APP_STATE_RECEIVED";
export const MAP_APP_STATE_RECEIVED = "MAP_APP_STATE_RECEIVED";
export const GET_FEED_IDS_SUCCESS = "GET_FEED_IDS_SUCCESS";
export const CAMERAS_RECEIVED = "CAMERAS_RECEIVED";
export const CAMERA_RECEIVED = "CAMERA_RECEIVED";
export const ORGS_RECEIVED = "ORGS_RECEIVED";
export const PINNED_ITEM_RECEIVED = "PINNED_ITEM_RECEIVED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const ENTITY_COLLECTION_RECEIVED = "ENTITY_COLLECTION_RECEIVED";
export const GET_FEED_IDS = "GET_FEED_IDS";
export const RULES_RECEIVED = "RULES_RECEIVED";
export const ENTITY_DATA_RECEIVED = "ENTITY_DATA_RECEIVED";
export const ENTITY_DATA_REMOVED = "ENTITY_DATA_REMOVED";
export const ENTITY_BATCH_RECEIVED = "ENTITY_BATCH_RECEIVED";
export const EVENTS_RECEIVED = "EVENTS_RECEIVED";

// OptionsDrawer
export const SET_MAP_STYLE_SUCCESS = "SET_MAP_STYLE_SUCCESS";
export const TOGGLE_MAP_OVERLAY = "TOGGLE_MAP_OVERLAY";
export const TOGGLE_ENTITY_LABELS = "TOGGLE_ENTITY_LABELS";

// CamerasListPanel
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const SHOW_LIST_PANEL = "SHOW_LIST_PANEL";
export const HIDE_LIST_PANEL = "HIDE_LIST_PANEL";
export const OPEN_CAMERA_DIALOG = "OPEN_CAMERA_DIALOG";
export const VIEW_LAST_PROFILE = "VIEW_LAST_PROFILE";

// CameraCard
export const SHOW_CAMERA_PROFILE = "SHOW_CAMERA_PROFILE";
export const ACTIVITY_DATA_RECEIVED = "ACTIVITY_DATA_RECEIVED";
export const CAMERA_ATTACHMENT_DATA_RECEIVED = "CAMERA_ATTACHMENT_DATA_RECEIVED";
export const RECEIVED_FOV = "RECEIVED_FOV";
export const RECEIVED_FOV_BATCH = "RECEIVED_FOV_BATCH";
export const RECEIVED_FOV_ITEM = "RECEIVED_FOV_ITEM";
export const REMOVED_FOV_ITEM = "REMOVED_FOV_ITEM";
export const SET_FOV_SUBSCRIPTION = "SET_FOV_SUBSCRIPTION";
export const CAMERAS_IN_RANGE_RECEIVED = "CAMERAS_IN_RANGE_RECEIVED";
export const CAMERAS_IN_RANGE_REMOVED = "CAMERAS_IN_RANGE_REMOVED";
export const CLEAR_FOV_FEED = "CLEAR_FOV_FEED";
export const SET_CAMERAS_IN_RANGE_SUBSCRIPTION = "SET_CAMERAS_IN_RANGE_SUBSCRIPTION";

// CameraProfile
export const HIDE_CAMERA_PROFILE = "HIDE_CAMERA_PROFILE";
export const SELECT_WIDGET = "SELECT_WIDGET";
export const UPDATE_ACTIVITY_FILTER_SUCCESS = "UPDATE_ACTIVITY_FILTER_SUCCESS";
export const SET_WIDGET_ORDER = "SET_WIDGET_ORDER";
export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const UNPIN_ITEM_SUCCESS = "UNPIN_ITEM_SUCCESS";
export const CAMERA_ATTACHMENT_DELETE_SUCCESS = "CAMERA_ATTACHMENT_DELETE_SUCCESS";
export const CLOSE_PIN_TO_DIALOG = "CLOSE_PIN_TO_DIALOG";
export const OPEN_PIN_TO_DIALOG = "OPEN_PIN_TO_DIALOG";
export const CAMERA_UPDATED = "CAMERA_UPDATED";
export const CAMERA_IN_RANGE_VIDEO_STREAM_RECEIVED = "CAMERA_IN_RANGE_VIDEO_STREAM_RECEIVED";
export const CAMERA_IN_RANGE_SUBSCRIPTION_RECEIVED = "CAMERA_IN_RANGE_SUBSCRIPTION_RECEIVED";
export const CAMERA_TO_DOCK_MODE = "CAMERA_TO_DOCK_MODE";

// CameraMap
export const SET_MAP_POSITION_SUCCESS = "SET_MAP_POSITION_SUCCESS";
export const SET_MAP_REFERENCE = "SET_MAP_REFERENCE";

// CameraMapLayers
export const TOGGLE_DISTANCE_TOOLS = "TOGGLE_DISTANCE_TOOLS";

// CameraList
export const GET_ALL_LISTS = "GET_ALL_LISTS";
export const LISTS_RECEIVED = "LISTS_RECEIVED";
export const LISTS_CREATED_BY_TEMPLATE = "LISTS_CREATED_BY_TEMPLATE";
export const STREAMED_LIST_RECEIVED = "STREAMED_LIST_RECEIVED";
export const STREAMED_LIST_UPDATED = "STREAMED_LIST_UPDATED";
export const CLEAR_CAMERA_LIST_DATA = "CLEAR_CAMERA_LIST_DATA";
export const UPDATE_LIST_CHECKBOX = "UPDATE_LIST_CHECKBOX";
export const LIST_UPDATED = "LIST_UPDATED";
export const LIST_DELETED = "LIST_DELETED";
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

// CameraDialog
export const CLOSE_CAMERA_DIALOG = "CLOSE_CAMERA_DIALOG";

// CameraCollection
export const ADD_TO_FILTER = "ADD_TO_FILTER";
export const REMOVE_FROM_FILTER = "REMOVE_FROM_FILTER";

// PinnedItemsDialog
// export const UPDATE_ITEM_SEARCH = "UPDATE_ITEM_SEARCH";
// export const SHOW_SEARCH_RESULTS = "SHOW_SEARCH_RESULTS";

// EntityProfile
export const SHOW_ENTITY_INFO = "SHOW_ENTITY_INFO";
export const ENTITY_ACTIVITY_DATA_RECEIVED = "ENTITY_ACTIVITY_DATA_RECEIVED";
export const ENTITY_ATTACHMENT_DATA_RECEIVED = "ENTITY_ATTACHMENT_DATA_RECEIVED";
export const UPDATE_VIEWING_HISTORY = "UPDATE_VIEWING_HISTORY";
export const DELETE_ENTITY_SUCCESS = "DELETE_ENTITY_SUCCESS";
export const TRACK_HISTORY_TOGGLED = "TRACK_HISTORY_TOGGLED";
export const OPEN_ENTITY_SHARE_DIALOG = "OPEN_ENTITY_SHARE_DIALOG";
export const CLOSE_ENTITY_SHARE_DIALOG = "CLOSE_ENTITY_SHARE_DIALOG";
export const ADDED_TO_MY_ITEMS = "ADDED_TO_MY_ITEMS";
export const REMOVED_FROM_MY_ITEMS = "REMOVED_FROM_MY_ITEMS";
export const OPEN_ATTACHMENT_DELETE = "OPEN_ATTACHMENT_DELETE";
export const CLOSE_ATTACHMENT_DELETE = "CLOSE_ATTACHMENT_DELETE";
export const GET_ENTITY_ACTIVITY_BATCH = "GET_ENTITY_ACTIVITY_BATCH";
export const SET_ENTITY_WIDGET_ORDER = "SET_ENTITY_WIDGET_ORDER";
// export const QUERY_DIALOG_ERROR = "QUERY_DIALOG_ERROR";
export const SET_ACTIVITY_SUBSCRIPTION = "SET_ACTIVITY_SUBSCRIPTION";
export const CLEAR_ACTIVITY_DATA = "CLEAR_ACTIVITY_DATA";
// export const RECEIVED_COMMENT_COUNT = "RECEIVED_COMMENT_COUNT";

// Camera Streaming
export const CAMERA_SUBSCRIPTION_RECEIVED = "CAMERA_SUBSCRIPTION_RECEIVED";
export const CAMERA_VIDEO_STREAM_RECEIVED = "CAMERA_VIDEO_STREAM_RECEIVED";

// Widget Launch
export const SET_WIDGET_LAUNCH_DATA = "SET_WIDGET_LAUNCH_DATA";
