"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_CURRENT_FEATURE = exports.SPOTLIGHT_SET = exports.SPOTLIGHT_RESTART = exports.SPOTLIGHT_REMOVE = exports.SET_MAP_TOOLS = exports.PATH_UPDATE = exports.PATH_DELETE = exports.PATHS_UPDATE = exports.ACTIVE_PATH_SET = void 0;
var UPDATE_CURRENT_FEATURE = "UPDATE_CURRENT_FEATURE";
exports.UPDATE_CURRENT_FEATURE = UPDATE_CURRENT_FEATURE;
var SET_MAP_TOOLS = "SET_MAP_TOOLS";
exports.SET_MAP_TOOLS = SET_MAP_TOOLS;
var PATH_UPDATE = "PATH_UPDATE";
exports.PATH_UPDATE = PATH_UPDATE;
var PATHS_UPDATE = "PATHS_UPDATE";
exports.PATHS_UPDATE = PATHS_UPDATE;
var PATH_DELETE = "PATH_DELETE";
exports.PATH_DELETE = PATH_DELETE;
var ACTIVE_PATH_SET = "ACTIVE_PATH_SET";
exports.ACTIVE_PATH_SET = ACTIVE_PATH_SET;
var SPOTLIGHT_SET = "SPOTLIGHT_SET";
exports.SPOTLIGHT_SET = SPOTLIGHT_SET;
var SPOTLIGHT_REMOVE = "SPOTLIGHT_REMOVE";
exports.SPOTLIGHT_REMOVE = SPOTLIGHT_REMOVE;
var SPOTLIGHT_RESTART = "SPOTLIGHT_RESTART";
exports.SPOTLIGHT_RESTART = SPOTLIGHT_RESTART;