"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.SUBSCRIPTION_DATA_UPDATED = exports.SUBSCRIPTION_DATA_REMOVED = exports.SUBSCRIPTION_DATA_RECEIVED = exports.SUBSCRIPTION_DATA_BATCH_RECEIVED = exports.SET_SUBSCRIPTION = void 0;
var SUBSCRIPTION_DATA_RECEIVED = "SUBSCRIPTION_DATA_RECEIVED";
exports.SUBSCRIPTION_DATA_RECEIVED = SUBSCRIPTION_DATA_RECEIVED;
var SUBSCRIPTION_DATA_REMOVED = "SUBSCRIPTION_DATA_REMOVED";
exports.SUBSCRIPTION_DATA_REMOVED = SUBSCRIPTION_DATA_REMOVED;
var SUBSCRIPTION_DATA_UPDATED = "SUBSCRIPTION_DATA_UPDATED";
exports.SUBSCRIPTION_DATA_UPDATED = SUBSCRIPTION_DATA_UPDATED;
var SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
exports.SET_SUBSCRIPTION = SET_SUBSCRIPTION;
var SUBSCRIPTION_DATA_BATCH_RECEIVED = "SUBSCRIPTION_DATA_BATCH_RECEIVED";
exports.SUBSCRIPTION_DATA_BATCH_RECEIVED = SUBSCRIPTION_DATA_BATCH_RECEIVED;