"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_SEARCH_VALUE = exports.UPDATE_SEARCH_RESULTS = exports.UPDATE_EVENT_TEMPLATE_SEARCH = exports.UPDATE_EVENT_SEARCH = exports.REMOVE_FROM_MAP_FILTERS = exports.CLEAR_SEARCH_RESULTS = exports.CLEAR_MAP_FILTERS = exports.ADD_TO_MAP_FILTERS = void 0;
var UPDATE_SEARCH_VALUE = "UPDATE_SEARCH_VALUE";
exports.UPDATE_SEARCH_VALUE = UPDATE_SEARCH_VALUE;
var UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
exports.UPDATE_SEARCH_RESULTS = UPDATE_SEARCH_RESULTS;
var CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
exports.CLEAR_SEARCH_RESULTS = CLEAR_SEARCH_RESULTS;
var ADD_TO_MAP_FILTERS = "ADD_TO_MAP_FILTERS";
exports.ADD_TO_MAP_FILTERS = ADD_TO_MAP_FILTERS;
var REMOVE_FROM_MAP_FILTERS = "REMOVE_FROM_MAP_FILTERS";
exports.REMOVE_FROM_MAP_FILTERS = REMOVE_FROM_MAP_FILTERS;
var CLEAR_MAP_FILTERS = "CLEAR_MAP_FILTERS";
exports.CLEAR_MAP_FILTERS = CLEAR_MAP_FILTERS;
var UPDATE_EVENT_SEARCH = "UPDATE_EVENT_SEARCH";
exports.UPDATE_EVENT_SEARCH = UPDATE_EVENT_SEARCH;
var UPDATE_EVENT_TEMPLATE_SEARCH = "UPDATE_EVENT_TEMPLATE_SEARCH";
exports.UPDATE_EVENT_TEMPLATE_SEARCH = UPDATE_EVENT_TEMPLATE_SEARCH;