// App
export const REPORT_TYPES_RECEIVED = "REPORT_TYPES_RECEIVED";

// TypeAheadFilter
export const TYPEAHEAD_FILTER = "TYPEAHEAD_FILTER";

// Report Builder
export const FIELD_DATA_RECEIVED = "FIELD_DATA_RECEIVED";
export const WIPE_ALL_FIELD_DATA = "WIPE_ALL_FIELD_DATA";
export const WIPE_FIELD_DATA = "WIPE_FIELD_DATA";
export const REPORT_DATA_RECEIVED = "REPORT_DATA_RECEIVED";
export const PAGE_RECEIVED = "PAGE_RECEIVED";
export const WIPE_REPORTS = "WIPE_REPORTS";
export const SUBMITTING_REPORT = "SUBMITTING_REPORT";
export const BUILDER_ERROR = "BUILDER_ERROR";

export const OPEN_REQUEST_DIALOG = "OPEN_REQUEST_DIALOG";
export const CLOSE_REQUEST_DIALOG = "CLOSE_REQUEST_DIALOG";

export const OPEN_PDF_REQUEST_DIALOG = "OPEN_PDF_REQUEST_DIALOG";
export const CLOSE_PDF_REQUEST_DIALOG = "CLOSE_PDF_REQUEST_DIALOG";

export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const REQUESTING_NEXT_PAGE = "REQUESTING_NEXT_PAGE";

export const REQUEST_DIALOG_IS_SUBMITTING = "REQUEST_DIALOG_IS_SUBMITTING";
export const REQUEST_DIALOG_SUBMIT_ERROR = "REQUEST_DIALOG_SUBMIT_ERROR";
export const REQUEST_DIALOG_SUBMIT_SUCCESS = "REQUEST_DIALOG_SUBMIT_SUCCESS";

export const PDF_REQUEST_DIALOG_IS_SUBMITTING = "PDF_REQUEST_DIALOG_IS_SUBMITTING";
export const PDF_REQUEST_DIALOG_SUBMIT_ERROR = "PDF_REQUEST_DIALOG_SUBMIT_ERROR";
export const PDF_REQUEST_DIALOG_SUBMIT_SUCCESS = "PDF_REQUEST_DIALOG_SUBMIT_SUCCESS";

export const TOGGLE_GENERATING_PDF = "TOGGLE_GENERATING_PDF";
