export const HYDRATE_USER_SUCCESS = "HYDRATE_USER_SUCCESS";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const IDENTITY_INVALIDATED = "IDENTITY_INVALIDATED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
