"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.SET_WEBRTC_PLAY_WEBSOCKET = exports.SET_WEBRTC_PLAY_VIDEO_TRACK = exports.SET_WEBRTC_PLAY_PEERCONNECTION = exports.SET_WEBRTC_PLAY_CONNECTED = exports.SET_WEBRTC_PLAY_AUDIO_TRACK = exports.RESET_WEBRTC = void 0;
var SET_WEBRTC_PLAY_WEBSOCKET = "SET_WEBRTC_PLAY_WEBSOCKET";
exports.SET_WEBRTC_PLAY_WEBSOCKET = SET_WEBRTC_PLAY_WEBSOCKET;
var SET_WEBRTC_PLAY_PEERCONNECTION = "SET_WEBRTC_PLAY_PEERCONNECTION";
exports.SET_WEBRTC_PLAY_PEERCONNECTION = SET_WEBRTC_PLAY_PEERCONNECTION;
var SET_WEBRTC_PLAY_CONNECTED = "SET_WEBRTC_PLAY_CONNECTED";
exports.SET_WEBRTC_PLAY_CONNECTED = SET_WEBRTC_PLAY_CONNECTED;
var SET_WEBRTC_PLAY_AUDIO_TRACK = "SET_WEBRTC_PLAY_AUDIO_TRACK";
exports.SET_WEBRTC_PLAY_AUDIO_TRACK = SET_WEBRTC_PLAY_AUDIO_TRACK;
var SET_WEBRTC_PLAY_VIDEO_TRACK = "SET_WEBRTC_PLAY_VIDEO_TRACK";
exports.SET_WEBRTC_PLAY_VIDEO_TRACK = SET_WEBRTC_PLAY_VIDEO_TRACK;
var RESET_WEBRTC = "RESET_WEBRTC";
exports.RESET_WEBRTC = RESET_WEBRTC;