"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.REOPEN_NOTIFICATIONS = exports.REOPEN_NOTIFICATION = exports.NOTIFICATION_REMOVED = exports.NOTIFICATION_RECEIVED = exports.NOTIFICATION_BATCH_RECEIVED = exports.INITIAL_NOTIFICATIONS_RECEIVED = exports.GET_ARCHIVE_SUCCESS = exports.GET_ARCHIVE_FAILED = exports.DUMP_ARCHIVE = exports.CLOSE_NOTIFICATIONS = exports.CLOSE_NOTIFICATION = void 0;
var INITIAL_NOTIFICATIONS_RECEIVED = "INITIAL_NOTIFICATIONS_RECEIVED";
exports.INITIAL_NOTIFICATIONS_RECEIVED = INITIAL_NOTIFICATIONS_RECEIVED;
var NOTIFICATION_BATCH_RECEIVED = "NOTIFICATION_BATCH_RECEIVED";
exports.NOTIFICATION_BATCH_RECEIVED = NOTIFICATION_BATCH_RECEIVED;
var NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";
exports.NOTIFICATION_RECEIVED = NOTIFICATION_RECEIVED;
var NOTIFICATION_REMOVED = "NOTIFICATION_REMOVED";
exports.NOTIFICATION_REMOVED = NOTIFICATION_REMOVED;
var CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
exports.CLOSE_NOTIFICATION = CLOSE_NOTIFICATION;
var CLOSE_NOTIFICATIONS = "CLOSE_NOTIFICATIONS";
exports.CLOSE_NOTIFICATIONS = CLOSE_NOTIFICATIONS;
var REOPEN_NOTIFICATION = "REOPEN_NOTIFICATION";
exports.REOPEN_NOTIFICATION = REOPEN_NOTIFICATION;
var REOPEN_NOTIFICATIONS = "REOPEN_NOTIFICATIONS";
exports.REOPEN_NOTIFICATIONS = REOPEN_NOTIFICATIONS;
var GET_ARCHIVE_SUCCESS = "GET_ARCHIVE_SUCCESS";
exports.GET_ARCHIVE_SUCCESS = GET_ARCHIVE_SUCCESS;
var GET_ARCHIVE_FAILED = "GET_ARCHIVE_FAILED";
exports.GET_ARCHIVE_FAILED = GET_ARCHIVE_FAILED;
var DUMP_ARCHIVE = "DUMP_ARCHIVE";
exports.DUMP_ARCHIVE = DUMP_ARCHIVE;