"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_CONTEXT_PROPERTY = exports.UPDATE_CONTEXT_LIST_CATEGORIES = exports.UPDATE_CONTEXT = exports.SUBSCRIPTION_DATA_RECEIVED = exports.SET_SUBSCRIPTION = exports.REMOVE_SUBSCRIPTION = exports.REMOVE_SUBSCRIBER = exports.REMOVE_CONTEXT = exports.ADD_SUBSCRIBER = exports.ADD_CONTEXT = void 0;
var SET_SUBSCRIPTION = "SET_SUBSCRIPTION";
exports.SET_SUBSCRIPTION = SET_SUBSCRIPTION;
var SUBSCRIPTION_DATA_RECEIVED = "SUBSCRIPTION_DATA_RECEIVED";
exports.SUBSCRIPTION_DATA_RECEIVED = SUBSCRIPTION_DATA_RECEIVED;
var ADD_CONTEXT = "ADD_CONTEXT";
exports.ADD_CONTEXT = ADD_CONTEXT;
var UPDATE_CONTEXT = "UPDATE_CONTEXT";
exports.UPDATE_CONTEXT = UPDATE_CONTEXT;
var UPDATE_CONTEXT_PROPERTY = "UPDATE_CONTEXT_PROPERTY";
exports.UPDATE_CONTEXT_PROPERTY = UPDATE_CONTEXT_PROPERTY;
var REMOVE_CONTEXT = "REMOVE_CONTEXT";
exports.REMOVE_CONTEXT = REMOVE_CONTEXT;
var REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION";
exports.REMOVE_SUBSCRIPTION = REMOVE_SUBSCRIPTION;
var REMOVE_SUBSCRIBER = "REMOVE_SUBSCRIBER";
exports.REMOVE_SUBSCRIBER = REMOVE_SUBSCRIBER;
var ADD_SUBSCRIBER = "ADD_SUBSCRIBER";
exports.ADD_SUBSCRIBER = ADD_SUBSCRIBER;
var UPDATE_CONTEXT_LIST_CATEGORIES = "UPDATE_CONTEXT_LIST_CATEGORIES";
exports.UPDATE_CONTEXT_LIST_CATEGORIES = UPDATE_CONTEXT_LIST_CATEGORIES;