export const CAMERA_GROUP_RECEIVED = "CAMERA_GROUP_RECEIVED";
export const CAMERA_GROUP_REMOVED = "CAMERA_GROUP_REMOVED";

// Widget Launch
export const SET_WIDGET_LAUNCH_DATA = "SET_WIDGET_LAUNCH_DATA";
