"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.RECEIVED_EVENT_COMMENT_COUNT = exports.INITIAL_EVENT_BATCH_RECEIVED = exports.EVENT_UPDATED = exports.EVENT_TYPES_RECEIVED = exports.EVENT_TEMPLATE_UPDATED = exports.EVENT_TEMPLATE_REMOVED = exports.EVENT_TEMPLATE_RECEIVED = exports.EVENT_REMOVED = exports.EVENT_RECEIVED = void 0;
var INITIAL_EVENT_BATCH_RECEIVED = "INITIAL_EVENT_BATCH_RECEIVED";
exports.INITIAL_EVENT_BATCH_RECEIVED = INITIAL_EVENT_BATCH_RECEIVED;
var EVENT_RECEIVED = "EVENT_RECEIVED";
exports.EVENT_RECEIVED = EVENT_RECEIVED;
var EVENT_REMOVED = "EVENT_REMOVED";
exports.EVENT_REMOVED = EVENT_REMOVED;
var EVENT_UPDATED = "EVENT_UPDATED";
exports.EVENT_UPDATED = EVENT_UPDATED;
var RECEIVED_EVENT_COMMENT_COUNT = "RECEIVED_EVENT_COMMENT_COUNT";
exports.RECEIVED_EVENT_COMMENT_COUNT = RECEIVED_EVENT_COMMENT_COUNT;
var EVENT_TYPES_RECEIVED = "EVENT_TYPES_RECEIVED";
exports.EVENT_TYPES_RECEIVED = EVENT_TYPES_RECEIVED;
var EVENT_TEMPLATE_RECEIVED = "EVENT_TEMPLATE_RECEIVED";
exports.EVENT_TEMPLATE_RECEIVED = EVENT_TEMPLATE_RECEIVED;
var EVENT_TEMPLATE_REMOVED = "EVENT_TEMPLATE_REMOVED";
exports.EVENT_TEMPLATE_REMOVED = EVENT_TEMPLATE_REMOVED;
var EVENT_TEMPLATE_UPDATED = "EVENT_TEMPLATE_UPDATED";
exports.EVENT_TEMPLATE_UPDATED = EVENT_TEMPLATE_UPDATED;