// App
export const FETCH_RULES_SUCCESS = "FETCH_RULES_SUCCESS";
export const FETCH_ORG_USERS_SUCCESS = "FETCH_ORG_USERS_SUCCESS";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_HEALTH_SYSTEMS_SUCCESS = "FETCH_HEALTH_SYSTEMS_SUCCESS";

// CreateEditRule
export const ADD_RULE_SUCCESS = "ADD_RULE_SUCCESS";

// Main
export const DELETE_RULE_SUCCESS = "DELETE_RULE_SUCCESS";
export const FILTER_TRIGGER_TOGGLE = "FILTER_TRIGGER_TOGGLE";

// RulesAppBar
export const TOGGLE_APP_SETTINGS_MENU = "TOGGLE_APP_SETTINGS_MENU";
export const TOGGLE_APPS_MENU = "TOGGLE_APPS_MENU";

//TypeAheadFilter
export const TYPEAHEAD_FILTER = "TYPEAHEAD_FILTER";

//ViewRule
export const UPDATE_RULE_SUCCESS = "UPDATE_RULE_SUCCESS";

export const TOGGLE_QUERYING = "TOGGLE_QUERYING";
export const UPDATE_TRACK_SEARCH = "UPDATE_TRACK_SEARCH";
export const QUERY_DIALOG_ERROR = "QUERY_DIALOG_ERROR";
export const SHOW_SEARCH_RESULTS = "SHOW_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
