export const UPDATE_SEARCH_VALUE = "UPDATE_SEARCH_VALUE";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const ADD_TO_MAP_FILTERS = "ADD_TO_MAP_FILTERS";
export const REMOVE_FROM_MAP_FILTERS = "REMOVE_FROM_MAP_FILTERS";
export const CLEAR_MAP_FILTERS = "CLEAR_MAP_FILTERS";
export const UPDATE_EVENT_SEARCH = "UPDATE_EVENT_SEARCH";
export const UPDATE_EVENT_TEMPLATE_SEARCH = "UPDATE_EVENT_TEMPLATE_SEARCH";
