"use strict";

var _Object$defineProperty = require("@babel/runtime-corejs3/core-js-stable/object/define-property");
_Object$defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_WAV_CAM_LABELS = exports.TOGGLE_WAV_CAM = exports.TOGGLE_OPEN = exports.TOGGLE_FIND_NEAREST = exports.TOGGLE_CLOSE = exports.SHOW_ALERT = exports.SET_ALERTS_TAB = exports.REOPEN_NOTIFICATION_FAILED = exports.REOPEN_NOTIFICATIONS_FAILED = exports.REMOVE_DOCKED_CAMERA = exports.HIDE_ALERT = exports.GET_ARCHIVE_SUCCESS = exports.GET_ARCHIVE_FAILED = exports.DOCK_APP_STATE_RECEIVED = exports.DOCKED_CAMERA_VIDEO_STREAM_RECEIVED = exports.DOCKED_CAMERA_SUBSCRIPTION_RECEIVED = exports.CLOSE_NOTIFICATION_FAILED = exports.CLOSE_NOTIFICATION_COMPLETE = exports.CLOSE_NOTIFICATIONS_FAILED = exports.CLOSE_NOTIFICATIONS_COMPLETE = exports.CLEAR_FIND_NEAREST = exports.CLEAR_CAMERA_STREAM = exports.CLEAR_CAMERA_REPLACE_MODE = exports.CAMERA_TO_DOCK_MODE = exports.CAMERA_PRIORITY_SET = exports.CAMERA_DOCKED = exports.CAMERAS_RECEIVED = void 0;
var SET_ALERTS_TAB = "SET_ALERTS_TAB";
exports.SET_ALERTS_TAB = SET_ALERTS_TAB;
var TOGGLE_CLOSE = "TOGGLE_CLOSE";
exports.TOGGLE_CLOSE = TOGGLE_CLOSE;
var TOGGLE_OPEN = "TOGGLE_OPEN";
exports.TOGGLE_OPEN = TOGGLE_OPEN;
var TOGGLE_WAV_CAM = "TOGGLE_WAV_CAM";
exports.TOGGLE_WAV_CAM = TOGGLE_WAV_CAM;
var CAMERA_TO_DOCK_MODE = "CAMERA_TO_DOCK_MODE";
exports.CAMERA_TO_DOCK_MODE = CAMERA_TO_DOCK_MODE;
var CLOSE_NOTIFICATION_FAILED = "CLOSE_NOTIFICATION_FAILED";
exports.CLOSE_NOTIFICATION_FAILED = CLOSE_NOTIFICATION_FAILED;
var CLOSE_NOTIFICATIONS_FAILED = "CLOSE_NOTIFICATIONS_FAILED";
exports.CLOSE_NOTIFICATIONS_FAILED = CLOSE_NOTIFICATIONS_FAILED;
var REOPEN_NOTIFICATION_FAILED = "REOPEN_NOTIFICATION_FAILED";
exports.REOPEN_NOTIFICATION_FAILED = REOPEN_NOTIFICATION_FAILED;
var REOPEN_NOTIFICATIONS_FAILED = "REOPEN_NOTIFICATIONS_FAILED";
exports.REOPEN_NOTIFICATIONS_FAILED = REOPEN_NOTIFICATIONS_FAILED;
var GET_ARCHIVE_FAILED = "GET_ARCHIVE_FAILED";
exports.GET_ARCHIVE_FAILED = GET_ARCHIVE_FAILED;
var GET_ARCHIVE_SUCCESS = "GET_ARCHIVE_SUCCESS";
exports.GET_ARCHIVE_SUCCESS = GET_ARCHIVE_SUCCESS;
var CLOSE_NOTIFICATION_COMPLETE = "CLOSE_NOTIFICATION_COMPLETE";
exports.CLOSE_NOTIFICATION_COMPLETE = CLOSE_NOTIFICATION_COMPLETE;
var CLOSE_NOTIFICATIONS_COMPLETE = "CLOSE_NOTIFICATIONS_COMPLETE";
exports.CLOSE_NOTIFICATIONS_COMPLETE = CLOSE_NOTIFICATIONS_COMPLETE;
var SHOW_ALERT = "SHOW_ALERT";
exports.SHOW_ALERT = SHOW_ALERT;
var HIDE_ALERT = "HIDE_ALERT";
exports.HIDE_ALERT = HIDE_ALERT;
var DOCK_APP_STATE_RECEIVED = "DOCK_APP_STATE_RECEIVED";
exports.DOCK_APP_STATE_RECEIVED = DOCK_APP_STATE_RECEIVED;
var TOGGLE_WAV_CAM_LABELS = "TOGGLE_WAV_CAM_LABELS";

// IMPORTANT: I have no idea why, but the camera dock breaks unless these actions are left here.
// It doesn't seem like any actions are using these, but as soon as I remove any of them, the dock breaks.
//////////// CAMERA DOCK /////////////////
exports.TOGGLE_WAV_CAM_LABELS = TOGGLE_WAV_CAM_LABELS;
var CAMERA_DOCKED = "CAMERA_DOCKED";
exports.CAMERA_DOCKED = CAMERA_DOCKED;
var REMOVE_DOCKED_CAMERA = "REMOVE_DOCKED_CAMERA";
exports.REMOVE_DOCKED_CAMERA = REMOVE_DOCKED_CAMERA;
var CAMERAS_RECEIVED = "CAMERAS_RECEIVED";
exports.CAMERAS_RECEIVED = CAMERAS_RECEIVED;
var CAMERA_PRIORITY_SET = "CAMERA_PRIORITY_SET";
exports.CAMERA_PRIORITY_SET = CAMERA_PRIORITY_SET;
var TOGGLE_FIND_NEAREST = "TOGGLE_FIND_NEAREST";
exports.TOGGLE_FIND_NEAREST = TOGGLE_FIND_NEAREST;
var CLEAR_FIND_NEAREST = "CLEAR_FIND_NEAREST";
exports.CLEAR_FIND_NEAREST = CLEAR_FIND_NEAREST;
var CLEAR_CAMERA_REPLACE_MODE = "CLEAR_CAMERA_REPLACE_MODE";
exports.CLEAR_CAMERA_REPLACE_MODE = CLEAR_CAMERA_REPLACE_MODE;
var DOCKED_CAMERA_VIDEO_STREAM_RECEIVED = "DOCKED_CAMERA_VIDEO_STREAM_RECEIVED";
exports.DOCKED_CAMERA_VIDEO_STREAM_RECEIVED = DOCKED_CAMERA_VIDEO_STREAM_RECEIVED;
var DOCKED_CAMERA_SUBSCRIPTION_RECEIVED = "DOCKED_CAMERA_SUBSCRIPTION_RECEIVED";
exports.DOCKED_CAMERA_SUBSCRIPTION_RECEIVED = DOCKED_CAMERA_SUBSCRIPTION_RECEIVED;
var CLEAR_CAMERA_STREAM = "CLEAR_CAMERA_STREAM";
exports.CLEAR_CAMERA_STREAM = CLEAR_CAMERA_STREAM;