export const BERTHS_RECEIVED = "BERTHS_RECEIVED";
export const BERTH_GROUPS_RECEIVED = "BERTH_GROUPS_RECEIVED";
export const BERTH_ASSIGNMENTS_RECEIVED = "BERTH_ASSIGNMENTS_RECEIVED";
export const BERTH_ASSIGNMENT_RECEIVED = "BERTH_ASSIGNMENT_RECEIVED";
export const BERTH_ASSIGNMENT_REMOVED = "BERTH_ASSIGNMENT_REMOVED";
export const BERTH_ASSIGNMENT_UPDATED = "BERTH_ASSIGNMENT_UPDATED";
