// General
export const OPERATION_FAILED = "OPERATION_FAILED";
export const CLEAR_ERROR = "CLEAR_ERROR";

// Global Users 
export const FETCH_USERS_SUCCESS = "USERS_FETCHED";
export const REFRESH_USERS_SUCCESS = "USERS_REFRESHED";

// Tabletop Session List
export const SESSION_ADDED = "SESSION_ADDED";
export const SESSION_DELETED = "SESSION_DELETED";
export const ALL_SESSIONS_LOADED = "ALL_SESSIONS_LOADED";
export const SESSION_INITIALIZING = "SESSION_INITIALIZING";
export const SESSION_INIT_FAILED = "SESSION_INIT_FAILED";
export const SESSION_AVERT_LOAD_STATUS_UPDATED = "SESSION_AVERT_LOAD_STATUS_UPDATED";
export const SET_NEW_SESSION_BASE_SIM_LOAD_TRIGGERED = "SET_NEW_SESSION_BASE_SIM_LOAD_TRIGGERED";
export const SET_NEW_SESSION_USER_MAPPINGS_TRIGGERED = "SET_NEW_SESSION_USER_MAPPINGS_TRIGGERED";
export const SET_DISPLAY_USER_MAPPINGS = "SET_DISPLAY_USER_MAPPINGS";
export const CLEAR_SESSION_TO_LOAD = "CLEAR_SESSION_TO_LOAD";

// Base simulations
export const BASE_SIMULATION_LIST_RECEIVED = "BASE_SIMULATION_LIST_RECEIVED";

// Tabletop Session
export const SESSION_RECEIVED = "SESSION_RECEIVED";
export const SESSION_UPDATED = "SESSION_UPDATED";
export const SESSION_SIMULATION_ADDED = "SESSION_SIMULATION_ADDED";
export const SESSION_SIMULATION_UPDATED = "SESSION_SIMULATION_UPDATED";
export const SESSION_SIMULATION_DELETED = "SESSION_SIMULATION_DELETED";
export const SESSION_SIMULATION_DATA_RECEIVED = "SESSION_SIMULATION_DATA_RECEIVED";
export const SESSION_SIMULATION_FRAMES_RECEIVED = "SESSION_SIMULATION_FRAMES_RECEIVED";
export const SESSION_SIMULATION_LOAD_TRIGGERED = "SESSION_SIMULATION_LOAD_TRIGGERED";
export const SESSION_SIMULATION_CURRENTFRAME_RECEIVED = "SESSION_SIMULATION_CURRENTFRAME_RECEIVED";
export const LOCATIONHISTORY_TRIGGERED = "LOCATIONHISTORY_TRIGGERED";
export const LOCATIONHISTORY_RECEIVED = "LOCATIONHISTORY_RECEIVED";
export const LOCATIONHISTORY_CLEAR = "LOCATIONHISTORY_CLEAR";

export const FLOORPLANS_RECEIVED = "FLOORPLANS_RECEIVED";
export const COMMUNICATION_RECEIVED = "COMMUNICATION_RECEIVED";

export const MAP_OPENED = "MAP_OPENED";
export const MAP_CLOSED = "MAP_CLOSED";

export const DISPLAY_FOV = "DISPLAY_FOV";
export const HIDE_FOV = "HIDE_FOV";

// Modifications
export const MODIFICATIONS_SUBSCRIBED = "MODIFICATIONS_SUBSCRIBED";
export const MODIFICATIONS_UNSUBSCRIBED = "MODIFICATIONS_UNSUBSCRIBED";
export const MODIFICATION_ADDED = "MODIFICATION_ADDED";
export const MODIFICATION_UPDATED = "MODIFICATION_UPDATED";
export const MODIFICATION_DELETED = "MODIFICATION_DELETED";

// Traces
export const TRACE_FEATURES_SET = "TRACE_FEATURES_SET";

// Component messages
export const SEND_COMPONENT_MESSAGE = "SEND_COMPONENT_MESSAGE";
export const CLEAR_COMPONENT_MESSAGE = "CLEAR_COMPONENT_MESSAGE";

// Local state
export const SET_LOCAL_STATE = "SET_LOCAL_STATE";
