export const CONTEXTUAL_CAMERA_RECEIVED = "CONTEXTUAL_CAMERA_RECEIVED";
export const CONTEXTUAL_CAMERA_REMOVED = "CONTEXTUAL_CAMERA_REMOVED";
export const CONTEXTUAL_CAMERA_BATCH_RECEIVED = "CONTEXTUAL_CAMERA_BATCH_RECEIVED";
