export const TOGGLE_REPLAY_MAP_VISIBLE = "TOGGLE_REPLAY_MAP_VISIBLE";
export const SET_REPLAY_MAP_REFERENCE = "SET_REPLAY_MAP_REFERENCE";
export const SET_REPLAY_MAP_ENTITIES = "SET_REPLAY_MAP_ENTITIES";
export const SET_REPLAY_MAP_OFFSET = "SET_REPLAY_MAP_OFFSET";
